### ISSUE TITLE
BT DONGLE10 (Cambridge Silicon Radio Ltd.) not working 

### ISSUE THREAD

**Issue by f1729** [dirkx/osx-hid2hci-for-bluetooth-csr8510-A10#5]
<img width="519" alt="Screen Shot 2020-10-23 at 10 42 48 PM" src="https://user-images.githubusercontent.com/23299193/97067257-3212f600-1581-11eb-9749-c514f66f7b23.png">
<img width="1152" alt="Screen Shot 2020-10-23 at 10 43 29 PM" src="https://user-images.githubusercontent.com/23299193/97067258-34755000-1581-11eb-802f-4e230cb0640b.png">

I'm having troubles with this dongle distribution ... any clue?

I don't have any idea what this error message means.
```
Unable to open device: e00002c5
```

**Comment by dirkx** [comment]
That error code suggess:
`
Kernel IOReturn.h | kIOReturnExclusiveAccess | 0xE00002C53758097093 | exclusive access and device already open
`
So check with lsof if anything has else is running too that may have claimed the device.

**Comment by f1729** [comment]
@dirkx Thanks for your reply and sorry to bother you, but I'm not sure how to get the process that is using the device, would you provide and example? I did my research but ... I didn't get how.

And If I got it, can I stop it without problems? I mean, this process wouldn't be using another USB devices?

**Comment by billcunha** [comment]
@f1729 Did you solve the problem with this device? I'm getting the same issue here.

**Comment by f1729** [comment]
@billcunha Sorry, I gave up, no idea how to solve it

**Comment by dirkx** [comment]
Correct. It needs to be ran once.

Until you powercycle the device or machine. 

You can let it run forever; it will sleep and not consume much resources but some memory until the device is re-seated.
